from fpdf import FPDF
import os
from datetime import datetime

REPORTS_DIR = os.path.join(os.path.dirname(__file__), "reports")
os.makedirs(REPORTS_DIR, exist_ok=True)

def get_verdict_color(verdict):
    colors = {
        "MALICIOUS": (200, 0, 0),
        "SUSPICIOUS": (200, 100, 0),
        "CLEAN": (0, 150, 0),
        "LOW RISK": (0, 150, 0),
        "ANOMALY DETECTED": (200, 100, 0),
        "NO ANOMALY": (0, 150, 0)
    }
    return colors.get(verdict, (0, 0, 0))

class SentinelIQReport(FPDF):

    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_fill_color(30, 30, 30)
        self.set_text_color(255, 255, 255)
        self.cell(0, 12, "SENTINELIQ - INVESTIGATION REPORT",
                  align="C", fill=True,
                  new_x="LMARGIN", new_y="NEXT")
        self.ln(3)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10,
                  f"Generated by SentinelIQ v4.0 | "
                  f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
                  align="C")

    def section_title(self, title):
        self.set_font("Helvetica", "B", 11)
        self.set_fill_color(240, 240, 240)
        self.set_text_color(0, 0, 0)
        self.cell(0, 8, title, fill=True,
                  new_x="LMARGIN", new_y="NEXT")
        self.ln(1)

    def key_value(self, key, value, color=None):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(80, 80, 80)
        self.cell(55, 7, f"{key}:", new_x="RIGHT", new_y="TOP")
        self.set_font("Helvetica", "", 10)
        if color:
            self.set_text_color(*color)
        else:
            self.set_text_color(0, 0, 0)
        self.multi_cell(0, 7, str(value), new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(0, 0, 0)

    def long_text(self, text):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(0, 0, 0)
        self.multi_cell(0, 6, str(text))
        self.ln(1)

def generate_pdf(investigation: dict) -> str:
    pdf = SentinelIQReport()
    pdf.set_margins(15, 15, 15)
    pdf.add_page()

    inv_id = investigation.get("investigation_id", "UNKNOWN")
    timestamp = investigation.get("timestamp", "UNKNOWN")
    input_type = investigation.get("input_type", "UNKNOWN").upper()
    input_value = investigation.get("input_value", "UNKNOWN")
    verdict = investigation.get("verdict", "UNKNOWN")
    risk_score = investigation.get("risk_score", 0)
    confidence = investigation.get("confidence_score", 0)
    severity = investigation.get("severity", "UNKNOWN")
    action = investigation.get("recommended_action", "UNKNOWN")

    verdict_color = get_verdict_color(verdict)

    # Section 1 - Investigation Details
    pdf.section_title("  INVESTIGATION DETAILS")
    pdf.key_value("Investigation ID", inv_id)
    pdf.key_value("Timestamp", timestamp)
    pdf.key_value("Input Type", input_type)
    pdf.key_value("Target", input_value)
    pdf.ln(3)

    # Section 2 - Verdict
    pdf.section_title("  VERDICT AND RISK ASSESSMENT")
    pdf.key_value("Verdict", verdict, color=verdict_color)
    pdf.key_value("Risk Score", f"{risk_score} / 100")
    pdf.key_value("Confidence Score", f"{confidence} / 100")
    pdf.key_value("Severity", severity, color=verdict_color)
    pdf.key_value("Recommended Action", action)
    pdf.ln(3)

    # Section 3 - Threat Intel
    threat_intel = investigation.get("threat_intel", {})
    if threat_intel:
        pdf.section_title("  THREAT INTELLIGENCE")
        for key, value in threat_intel.items():
            if key != "explainability" and not isinstance(value, dict):
                pdf.key_value(key.replace("_", " ").title(), str(value))
        pdf.ln(3)

    # Section 4 - MITRE Mapping
    mitre = investigation.get("mitre_mapping", [])
    if mitre:
        pdf.section_title("  MITRE ATT&CK MAPPING")
        if isinstance(mitre, list):
            for item in mitre:
                if isinstance(item, dict):
                    tech_id = item.get("technique_id", "")
                    score = item.get("score", "")
                    pdf.key_value(tech_id, f"Confidence: {score}")
        elif isinstance(mitre, dict):
            tech_id = mitre.get("technique_id", "")
            name = mitre.get("name", "")
            pdf.key_value(tech_id, name)
        pdf.ln(3)

    # Section 5 - AI Explanation
    ai_data = investigation.get("ai_explanation", {})
    if ai_data:
        pdf.section_title("  AI EXPLANATION (RAG-GROUNDED)")
        explanation = ai_data.get("explanation", "")
        primary_mitre = ai_data.get("primary_mitre", "")
        grounded = ai_data.get("grounded", False)
        ai_model = ai_data.get("ai_model", "")
        pdf.key_value("Primary MITRE", primary_mitre)
        pdf.key_value("AI Model", ai_model)
        pdf.key_value("RAG Grounded", str(grounded))
        pdf.ln(2)
        pdf.long_text(explanation)
        pdf.ln(3)

    # Save PDF
    filename = f"{inv_id}.pdf"
    filepath = os.path.join(REPORTS_DIR, filename)
    pdf.output(filepath)
    print(f"[PDF] Report generated: {filepath}")
    return filepath
